// angular/src/app/shared/preview/pptx-viewer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  OnDestroy,
  computed,
  effect,
  input,
  signal,
  viewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { PPTXViewer } from 'pptxviewjs';

@Component({
  selector: 'app-pptx-viewer',
  standalone: true,
  imports: [CommonModule, NzButtonModule, NzIconModule],
  templateUrl: './pptx-viewer.component.html',
  styleUrls: ['./pptx-viewer.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PptxViewerComponent implements OnDestroy {
  data = input.required<ArrayBuffer>();
  fileName = input('');

  readonly canvasRef = viewChild<ElementRef<HTMLCanvasElement>>('slideCanvas');

  readonly slideCount = signal(0);
  readonly currentSlide = signal(0);
  readonly isLoading = signal(true);
  readonly isRendering = signal(false);
  readonly error = signal('');
  readonly zoom = signal(1);

  readonly slideLabel = computed(() => `${this.currentSlide() + 1} / ${this.slideCount() || 0}`);
  readonly zoomLabel = computed(() => `${Math.round(this.zoom() * 100)}%`);
  readonly canGoPrev = computed(() => this.currentSlide() > 0);
  readonly canGoNext = computed(() => this.currentSlide() < this.slideCount() - 1);
  readonly visiblePageIndexes = computed(() => {
    const total = this.slideCount();
    const current = this.currentSlide();
    const maxVisible = 10;

    if (total <= maxVisible) {
      return Array.from({ length: total }, (_, index) => index);
    }

    const half = Math.floor(maxVisible / 2);
    let start = Math.max(0, current - half);
    let end = Math.min(total - 1, start + maxVisible - 1);

    if (end - start < maxVisible - 1) {
      start = Math.max(0, end - maxVisible + 1);
    }

    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  });

  readonly hasLeftEllipsis = computed(() => this.visiblePageIndexes()[0] > 0);
  readonly hasRightEllipsis = computed(() => this.visiblePageIndexes()[this.visiblePageIndexes().length - 1] < this.slideCount() - 1);

  private viewer: PPTXViewer | null = null;
  private renderToken = 0;

  constructor() {
    effect(() => {
      const data = this.data();
      const canvas = this.canvasRef()?.nativeElement;

      if (!data?.byteLength || !canvas) {
        return;
      }

      void this.loadPresentation(data, canvas);
    });
  }

  async prevSlide() {
    if (!this.canGoPrev()) return;
    await this.renderSlide(this.currentSlide() - 1);
  }

  async nextSlide() {
    if (!this.canGoNext()) return;
    await this.renderSlide(this.currentSlide() + 1);
  }

  async goToSlide(index: number) {
    if (index < 0 || index >= this.slideCount()) return;
    await this.renderSlide(index);
  }

  async zoomIn() {
    if (this.zoom() >= 2) return;
    this.zoom.update(value => Math.min(2, value + 0.25));
    await this.renderSlide(this.currentSlide());
  }

  async zoomOut() {
    if (this.zoom() <= 0.5) return;
    this.zoom.update(value => Math.max(0.5, value - 0.25));
    await this.renderSlide(this.currentSlide());
  }

  async resetZoom() {
    if (this.zoom() === 1) return;
    this.zoom.set(1);
    await this.renderSlide(this.currentSlide());
  }

  pageTrackBy = (index: number) => index;

  ngOnDestroy() {
    this.renderToken++;
    this.disposeViewer();
  }

  private async loadPresentation(data: ArrayBuffer, canvas: HTMLCanvasElement) {
    const token = ++this.renderToken;
    this.disposeViewer();

    this.isLoading.set(true);
    this.isRendering.set(false);
    this.error.set('');
    this.slideCount.set(0);
    this.currentSlide.set(0);
    this.zoom.set(1);

    try {
      const viewer = new PPTXViewer({
        canvas,
        debug: false,
        slideSizeMode: 'fit',
        backgroundColor: '#ffffff',
        autoRenderFirstSlide: false,
      });

      await viewer.loadFile(data.slice(0));

      if (token !== this.renderToken) {
        viewer.destroy();
        return;
      }

      this.viewer = viewer;
      this.slideCount.set(viewer.getSlideCount());
      await this.renderSlide(0, token);
    } catch (error: unknown) {
      if (token !== this.renderToken) {
        return;
      }

      console.error('PPTX render error:', error);
      this.error.set(error instanceof Error ? error.message : 'PPTX 预览加载失败');
    } finally {
      if (token === this.renderToken) {
        this.isLoading.set(false);
      }
    }
  }

  private async renderSlide(index: number, token = this.renderToken) {
    if (!this.viewer) return;

    this.isRendering.set(true);

    try {
      const canvas = this.canvasRef()?.nativeElement;
      if (!canvas) {
        return;
      }

      await this.viewer.render(canvas, {
        slideIndex: index,
        scale: this.zoom(),
        quality: 'high',
      });

      if (token !== this.renderToken) {
        return;
      }

      this.currentSlide.set(this.viewer.getCurrentSlideIndex());
      this.error.set('');
    } catch (error: unknown) {
      if (token !== this.renderToken) {
        return;
      }

      console.error('PPTX slide render error:', error);
      this.error.set(error instanceof Error ? error.message : 'PPTX 页面渲染失败');
    } finally {
      if (token === this.renderToken) {
        this.isRendering.set(false);
      }
    }
  }

  private disposeViewer() {
    if (!this.viewer) return;

    this.viewer.destroy();
    this.viewer = null;
  }
}

<div class="pptx-viewer">
  @if (error()) {
    <div class="viewer-error">{{ error() }}</div>
  } @else {
    <div class="viewer-toolbar">
      <div class="toolbar-group">
        <button nz-button nzSize="small" (click)="prevSlide()" [disabled]="!canGoPrev() || isLoading() || isRendering()">
          <span nz-icon nzType="left"></span>
        </button>
        <span class="viewer-status">{{ slideLabel() }}</span>
        <button nz-button nzSize="small" (click)="nextSlide()" [disabled]="!canGoNext() || isLoading() || isRendering()">
          <span nz-icon nzType="right"></span>
        </button>
      </div>

      <div class="toolbar-group">
        <button nz-button nzSize="small" (click)="zoomOut()" [disabled]="zoom() <= 0.5 || isLoading() || isRendering()">
          <span nz-icon nzType="zoom-out"></span>
        </button>
        <button nz-button nzSize="small" (click)="resetZoom()" [disabled]="zoom() === 1 || isLoading() || isRendering()">
          {{ zoomLabel() }}
        </button>
        <button nz-button nzSize="small" (click)="zoomIn()" [disabled]="zoom() >= 2 || isLoading() || isRendering()">
          <span nz-icon nzType="zoom-in"></span>
        </button>
      </div>
    </div>

    <div class="slide-stage">
      <canvas #slideCanvas class="slide-canvas" [class.hidden]="isLoading()"></canvas>

      @if (isLoading()) {
        <div class="stage-placeholder">正在加载 PPTX…</div>
      }

      @if (isRendering()) {
        <div class="rendering-mask">正在渲染幻灯片…</div>
      }
    </div>

    @if (slideCount() > 1) {
      <div class="page-strip">
        @if (hasLeftEllipsis()) {
          <button type="button" class="page-pill" (click)="goToSlide(0)">1</button>
          <span class="page-ellipsis">...</span>
        }
        @for (pageIndex of visiblePageIndexes(); track pageTrackBy(pageIndex)) {
          <button
            type="button"
            class="page-pill"
            [class.active]="pageIndex === currentSlide()"
            (click)="goToSlide(pageIndex)"
          >
            {{ pageIndex + 1 }}
          </button>
        }
        @if (hasRightEllipsis()) {
          <span class="page-ellipsis">...</span>
          <button type="button" class="page-pill" (click)="goToSlide(slideCount() - 1)">{{ slideCount() }}</button>
        }
      </div>
    }
  }
</div>

// student-react/src/components/viewers/PptxViewer.tsx
import { useEffect, useRef, useState, useCallback, useMemo } from 'react';
import { ChevronLeft, ChevronRight, ZoomIn, ZoomOut } from 'lucide-react';
import { PPTXViewer as PPTXViewerLib } from 'pptxviewjs';

interface PptxViewerProps {
  data: ArrayBuffer;
  fileName: string;
}

export function PptxViewer({ data }: PptxViewerProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const viewerRef = useRef<PPTXViewerLib | null>(null);
  const renderTokenRef = useRef(0);

  const [slideCount, setSlideCount] = useState(0);
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [isRendering, setIsRendering] = useState(false);
  const [error, setError] = useState('');
  const [zoom, setZoom] = useState(1);

  const slideLabel = `${currentSlide + 1} / ${slideCount || 0}`;
  const zoomLabel = `${Math.round(zoom * 100)}%`;

  const canGoPrev = currentSlide > 0;
  const canGoNext = currentSlide < slideCount - 1;

  const visiblePageIndexes = useMemo(() => {
    const total = slideCount;
    const current = currentSlide;
    const maxVisible = 10;

    if (total <= maxVisible) {
      return Array.from({ length: total }, (_, i) => i);
    }

    const half = Math.floor(maxVisible / 2);
    let start = Math.max(0, current - half);
    let end = Math.min(total - 1, start + maxVisible - 1);

    if (end - start < maxVisible - 1) {
      start = Math.max(0, end - maxVisible + 1);
    }

    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  }, [slideCount, currentSlide]);

  const hasLeftEllipsis = visiblePageIndexes[0] > 0;
  const hasRightEllipsis =
    visiblePageIndexes.length > 0 && visiblePageIndexes[visiblePageIndexes.length - 1] < slideCount - 1;

  const renderSlide = useCallback(async (index: number, currentZoom: number, token: number) => {
    if (!viewerRef.current) return;
    setIsRendering(true);
    try {
      const canvas = canvasRef.current;
      if (!canvas) return;
      await viewerRef.current.render(canvas, {
        slideIndex: index,
        scale: currentZoom,
        quality: 'high',
      });
      if (token !== renderTokenRef.current) return;
      setCurrentSlide(viewerRef.current.getCurrentSlideIndex());
      setError('');
    } catch (e: unknown) {
      if (token !== renderTokenRef.current) return;
      console.error('PPTX slide render error:', e);
      setError(e instanceof Error ? e.message : 'PPTX 页面渲染失败');
    } finally {
      if (token === renderTokenRef.current) {
        setIsRendering(false);
      }
    }
  }, []);

  // Load presentation
  useEffect(() => {
    const token = ++renderTokenRef.current;

    // Dispose previous viewer
    if (viewerRef.current) {
      viewerRef.current.destroy();
      viewerRef.current = null;
    }

    const canvas = canvasRef.current;
    if (!canvas || !data.byteLength) return;

    setIsLoading(true);
    setIsRendering(false);
    setError('');
    setSlideCount(0);
    setCurrentSlide(0);
    setZoom(1);

    const loadPresentation = async () => {
      try {
        const viewer = new PPTXViewerLib({
          canvas,
          debug: false,
          slideSizeMode: 'fit',
          backgroundColor: '#ffffff',
          autoRenderFirstSlide: false,
        });

        await viewer.loadFile(data.slice(0));

        if (token !== renderTokenRef.current) {
          viewer.destroy();
          return;
        }

        viewerRef.current = viewer;
        setSlideCount(viewer.getSlideCount());
        await renderSlide(0, 1, token);
      } catch (e: unknown) {
        if (token !== renderTokenRef.current) return;
        console.error('PPTX render error:', e);
        setError(e instanceof Error ? e.message : 'PPTX 预览加载失败');
      } finally {
        if (token === renderTokenRef.current) {
          setIsLoading(false);
        }
      }
    };

    loadPresentation();

    return () => {
      renderTokenRef.current++;
      if (viewerRef.current) {
        viewerRef.current.destroy();
        viewerRef.current = null;
      }
    };
  }, [data, renderSlide]);

  const handlePrevSlide = async () => {
    if (!canGoPrev) return;
    const token = renderTokenRef.current;
    await renderSlide(currentSlide - 1, zoom, token);
  };

  const handleNextSlide = async () => {
    if (!canGoNext) return;
    const token = renderTokenRef.current;
    await renderSlide(currentSlide + 1, zoom, token);
  };

  const handleGoToSlide = async (index: number) => {
    if (index < 0 || index >= slideCount) return;
    const token = renderTokenRef.current;
    await renderSlide(index, zoom, token);
  };

  const handleZoomIn = async () => {
    if (zoom >= 2) return;
    const newZoom = Math.min(2, zoom + 0.25);
    setZoom(newZoom);
    await renderSlide(currentSlide, newZoom, renderTokenRef.current);
  };

  const handleZoomOut = async () => {
    if (zoom <= 0.5) return;
    const newZoom = Math.max(0.5, zoom - 0.25);
    setZoom(newZoom);
    await renderSlide(currentSlide, newZoom, renderTokenRef.current);
  };

  const handleResetZoom = async () => {
    if (zoom === 1) return;
    setZoom(1);
    await renderSlide(currentSlide, 1, renderTokenRef.current);
  };

  return (
    <div className="pptx-viewer-container">
      {error ? (
        <div className="file-viewer-error">{error}</div>
      ) : (
        <>
          {/* Toolbar */}
          <div className="file-viewer-toolbar">
            <div className="flex items-center gap-2">
              <button
                className="viewer-toolbar-btn"
                onClick={handlePrevSlide}
                disabled={!canGoPrev || isLoading || isRendering}
              >
                <ChevronLeft className="h-4 w-4" />
              </button>
              <span className="text-sm text-secondary min-w-[72px] text-center font-semibold">{slideLabel}</span>
              <button
                className="viewer-toolbar-btn"
                onClick={handleNextSlide}
                disabled={!canGoNext || isLoading || isRendering}
              >
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
            <div className="flex items-center gap-2">
              <button className="viewer-toolbar-btn" onClick={handleZoomOut} disabled={zoom <= 0.5 || isLoading || isRendering}>
                <ZoomOut className="h-4 w-4" />
              </button>
              <button className="viewer-toolbar-btn" onClick={handleResetZoom} disabled={zoom === 1 || isLoading || isRendering}>
                <span className="text-xs font-medium">{zoomLabel}</span>
              </button>
              <button className="viewer-toolbar-btn" onClick={handleZoomIn} disabled={zoom >= 2 || isLoading || isRendering}>
                <ZoomIn className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Slide stage */}
          <div className="pptx-slide-stage">
            <canvas
              ref={canvasRef}
              className="pptx-slide-canvas"
              style={{ visibility: isLoading ? 'hidden' : 'visible' }}
            />
            {isLoading && (
              <div className="file-viewer-loading">
                <div className="loading-spinner" />
                <p className="mt-4 text-secondary text-sm">正在加载 PPTX…</p>
              </div>
            )}
            {isRendering && !isLoading && (
              <div className="pptx-rendering-mask">正在渲染幻灯片…</div>
            )}
          </div>

          {/* Page strip */}
          {slideCount > 1 && (
            <div className="pptx-page-strip">
              {hasLeftEllipsis && (
                <>
                  <button className="pptx-page-pill" onClick={() => handleGoToSlide(0)}>1</button>
                  <span className="pptx-page-ellipsis">...</span>
                </>
              )}
              {visiblePageIndexes.map(idx => (
                <button
                  key={idx}
                  className={`pptx-page-pill ${idx === currentSlide ? 'active' : ''}`}
                  onClick={() => handleGoToSlide(idx)}
                >
                  {idx + 1}
                </button>
              ))}
              {hasRightEllipsis && (
                <>
                  <span className="pptx-page-ellipsis">...</span>
                  <button className="pptx-page-pill" onClick={() => handleGoToSlide(slideCount - 1)}>
                    {slideCount}
                  </button>
                </>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
