// student-react/src/components/viewers/WordViewer.tsx
import { useEffect, useState } from 'react';
import DOMPurify from 'dompurify';

interface WordViewerProps {
  data: ArrayBuffer;
  fileName: string;
}

export function WordViewer({ data }: WordViewerProps) {
  const [htmlContent, setHtmlContent] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;
    const parseWord = async () => {
      try {
        setIsLoading(true);
        setError('');
        const mammoth = await import('mammoth');
        const result = await mammoth.default.convertToHtml({ arrayBuffer: data });
        if (cancelled) return;
        const clean = DOMPurify.sanitize(result.value);
        setHtmlContent(clean);
        if (result.messages.length > 0) {
          console.warn('Mammoth warnings:', result.messages);
        }
      } catch (e: any) {
        if (cancelled) return;
        console.error('Word parse error:', e);
        setError(e.message || 'Word 文档解析失败');
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    };
    parseWord();
    return () => { cancelled = true; };
  }, [data]);

  if (isLoading) {
    return (
      <div className="file-viewer-loading">
        <div className="loading-spinner" />
        <p className="mt-4 text-secondary text-sm">正在解析 Word 文档…</p>
      </div>
    );
  }

  if (error) {
    return <div className="file-viewer-error">{error}</div>;
  }

  return (
    <div className="word-viewer-content">
      <div
        className="word-viewer-html prose prose-sm max-w-none"
        dangerouslySetInnerHTML={{ __html: htmlContent }}
      />
    </div>
  );
}

// angular/src/app/shared/preview/word-viewer.component.ts
import { Component, signal, effect, input, inject, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Component({
  selector: 'app-word-viewer',
  standalone: true,
  imports: [CommonModule, NzSpinModule],
  templateUrl: './word-viewer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WordViewerComponent {
  data = input.required<ArrayBuffer>();
  fileName = input('');

  htmlContent = signal<SafeHtml>('');
  isLoading = signal(true);
  error = signal('');

  private readonly sanitizer = inject(DomSanitizer);

  constructor() {
    effect(() => {
      const d = this.data();
      if (d && d.byteLength > 0) {
        this.parseWord(d);
      }
    });
  }

  private async parseWord(data: ArrayBuffer) {
    try {
      this.isLoading.set(true);
      this.error.set('');

      const mammoth = await import('mammoth');
      const result = await mammoth.convertToHtml({ arrayBuffer: data });
      const safeHtml = this.sanitizer.bypassSecurityTrustHtml(result.value);
      this.htmlContent.set(safeHtml);

      if (result.messages.length > 0) {
        console.warn('Mammoth warnings:', result.messages);
      }
    } catch (e: any) {
      console.error('Word parse error:', e);
      this.error.set(e.message || 'Failed to parse Word document');
    } finally {
      this.isLoading.set(false);
    }
  }
}

<div class="word-viewer">
  <nz-spin *ngIf="isLoading()" nzSimple class="viewer-spinner"></nz-spin>
  <div *ngIf="error()" class="viewer-error">{{ error() }}</div>
  <div *ngIf="!isLoading() && !error()" class="word-content" [innerHTML]="htmlContent()"></div>
</div>
